spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/city_ms_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver