---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8010  
eureka:
  instance:
    hostname: eurekahost 
  client:
    # registerWithEureka e fetchRegistry estao false para evitar erros no log quando utiliza somente um servidor Eureka
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/